/**
 * settlementTypes.ts
 * ───────────────────
 * All TypeScript types for the Sumsuma Settlement Engine.
 * These mirror the Firestore document schemas exactly.
 *
 * Collections (prefixed 'se_' to avoid collision with treasury settlement_obligations):
 *   se_obligations              — per-payout settlement obligations
 *   settlement_batches          — grouped daily batches per provider/currency
 *   settlement_movements        — immutable ledger of settlement actions
 *   settlement_alerts           — overdue/mismatch/exposure alerts
 *   settlement_reconciliation_reports — partner-reported vs internal comparison
 */

// ─────────────────────────────────────────────
// ENUMERATIONS
// ─────────────────────────────────────────────

/** Which party owes money */
export type SettlementDirection = 'OWED_TO_PARTNER' | 'OWED_FROM_PARTNER';

/** Lifecycle of a single settlement obligation */
export type SettlementStatus =
  | 'OPEN'
  | 'BATCHED'
  | 'PROCESSING'
  | 'SETTLED'
  | 'FAILED'
  | 'CANCELLED';

/** Lifecycle of a settlement batch */
export type SettlementBatchStatus = 'OPEN' | 'PROCESSING' | 'SETTLED' | 'FAILED';

/** Types of immutable ledger movements */
export type SettlementMovementType =
  | 'SETTLEMENT_OPENED'
  | 'SETTLEMENT_BATCHED'
  | 'SETTLEMENT_SETTLED'
  | 'SETTLEMENT_FAILED'
  | 'SETTLEMENT_REBALANCED'
  | 'SETTLEMENT_ADJUSTED';

/** Alert types generated by the settlement engine */
export type SettlementAlertType =
  | 'SETTLEMENT_OVERDUE'
  | 'SETTLEMENT_MISMATCH'
  | 'NEGATIVE_EXPOSURE'
  | 'BATCH_FAILURE';

/** Alert severity */
export type SettlementAlertSeverity = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

/** Alert lifecycle */
export type SettlementAlertStatus = 'OPEN' | 'RESOLVED' | 'SUPPRESSED';

/** Reconciliation report result */
export type SettlementReconciliationStatus = 'MATCHED' | 'MISMATCH' | 'PENDING';

/** Supported payout providers */
export type SettlementProvider =
  | 'CHAPA'
  | 'TELEBIRR'
  | 'BANK_DASHEN'
  | 'BANK_AWASH'
  | 'BANK_CBE'
  | 'BANK_ABYSSINIA';

/** Supported currencies */
export type SettlementCurrency = 'ETB' | 'USD' | 'EUR' | 'GBP';

// ─────────────────────────────────────────────
// CORE DOCUMENTS
// ─────────────────────────────────────────────

/** Firestore: se_obligations/{obligationId} */
export interface SettlementObligation {
  obligationId: string;
  provider: SettlementProvider | string;
  currency: SettlementCurrency | string;
  direction: SettlementDirection;
  amount: number;
  referenceType: 'PAYOUT_TRANSACTION' | 'MANUAL' | string;
  referenceId: string;          // txId or manual reference
  status: SettlementStatus;
  createdAt: string;
  dueAt: string;
  settledAt: string | null;
  batchId: string | null;
  notes?: string;
}

/** Firestore: settlement_batches/{batchId} */
export interface SettlementBatch {
  batchId: string;
  provider: SettlementProvider | string;
  currency: SettlementCurrency | string;
  totalAmount: number;
  obligationCount: number;
  status: SettlementBatchStatus;
  createdAt: string;
  settledAt: string | null;
  notes?: string;
}

/** Firestore: settlement_movements/{movementId} — immutable ledger */
export interface SettlementMovement {
  movementId: string;
  type: SettlementMovementType;
  provider: string;
  currency: string;
  amount: number;
  obligationId: string | null;
  batchId: string | null;
  createdAt: string;
  createdBy: string;
}

/** Firestore: settlement_alerts/{alertId} */
export interface SettlementAlert {
  alertId: string;
  type: SettlementAlertType;
  provider: string;
  currency: string;
  severity: SettlementAlertSeverity;
  message: string;
  status: SettlementAlertStatus;
  createdAt: string;
  resolvedAt: string | null;
  resolvedBy?: string;
}

/** Firestore: settlement_reconciliation_reports/{reportId} */
export interface SettlementReconciliationReport {
  reportId: string;
  provider: string;
  currency: string;
  date: string;
  expectedAmount: number;
  reportedAmount: number;
  difference: number;
  status: SettlementReconciliationStatus;
  createdAt: string;
}

// ─────────────────────────────────────────────
// FILTERS & SUMMARIES
// ─────────────────────────────────────────────

export interface ObligationFilters {
  provider?: string;
  currency?: string;
  status?: SettlementStatus;
  startDate?: string;
  endDate?: string;
}

export interface BatchFilters {
  provider?: string;
  currency?: string;
  status?: SettlementBatchStatus;
}

export interface AlertFilters {
  type?: SettlementAlertType;
  severity?: SettlementAlertSeverity;
  status?: SettlementAlertStatus;
}

export interface ReconciliationFilters {
  provider?: string;
  status?: SettlementReconciliationStatus;
}

export interface SettlementOverview {
  totalOpenObligations: number;
  totalOpenAmount: number;
  totalBatchedAmount: number;
  totalSettledToday: number;
  overdueAlertsCount: number;
  mismatchedReportsCount: number;
  openBatchesCount: number;
}
